//> using scala 3.8.2
//> using option -Xmax-inlines:128
//> using option -no-indent
//> using option -old-syntax
//> using option -Wconf:name=PatternMatchExhaustivity:e,name=MatchCaseUnreachable:e
//> using dep dev.zio::zio:2.1.24
//> using dep com.yoohaemin::decrel-zquery-next:0.2.0
//> using dep com.github.ghostdogpr::caliban:3.0.0
//> using dep io.github.gaelrenoux::tranzactio-anorm:5.6.0
//> using dep com.h2database:h2:2.3.232
//> using test.dep org.scalameta::munit:1.2.4
